---
type: showroom

# Set the left column width to 30%
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: instructions

tabs:
  - name: Terminal
    path: /terminal
    port: 443
  - name: Quarkus Community
    url: 'https://quarkus.io/'

antora:
  name: modules
  dir: www
  modules:
  - name: module-01
    label: "Module 1: Deploy people app to OpenShift"
    solveButton: true
    scripts:
    - solve
    - validation
  - name: module-02
    label: "Module 2: Advanced Quarkus (Panache, Monitoring)"
    solveButton: true
    scripts:
    - solve
    - validation
