:imagesdir: ../assets/images

= What is Quarkus?
:navtitle: What is Quarkus?

Quarkus is a Kubernetes Native Java stack tailored for GraalVM & OpenJDK HotSpot, crafted from the best of breed Java libraries and standards. Amazingly fast boot time, incredibly low RSS memory (not just heap size!) offering near instant scale up and high density memory utilization in container orchestration platforms like Kubernetes. Quarkus uses a technique called https://quarkus.io/container-first[compile time boot^] and offers a unified imperative and reactive programming model and a number of other https://quarkus.io/developer-joy/[developer features^] like Live Reload to bring _real joy_ to your development.

Red Hat offers the fully supported https://access.redhat.com/products/quarkus/[Red Hat build of Quarkus^] with support and maintenance of Quarkus. In this workhop, you will use Quarkus to develop Kubernetes-native microservices and deploy them to OpenShift.

Throughout this lab you'll discover how Quarkus can make your development of cloud native apps faster and more productive.
== Workshop Overview

TODO: describe the upcoming content sections, time expectations per section, list of takeaways
